// app/dashboard/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'

interface DashboardStats {
  summary: {
    totalConsultations: number
    totalEpisodes: number
    totalProfessionals: number
    totalFiles: number
  }
  bySpecialty: Array<{ name: string; count: number }>
  byClinic: Array<{ name: string; count: number }>
  byYear: Array<{ year: string; count: number }>
  byProfessional: Array<{ name: string; specialty: string; count: number }>
  byMonth: Array<{ month: string; count: number }>
  recentConsultations: Array<{
    id: string
    date: string
    professionalName: string
    specialty: string
  }>
  recentEpisodes: Array<{
    id: string
    date: string
    title: string
  }>
  topRatedProfessionals: Array<{
    id: string
    name: string
    specialty: string
    averageRating: number
    totalRatings: number
  }>
}

export default function DashboardPage() {
  const { data: session, status } = useSession()
  const router = useRouter()
  const [stats, setStats] = useState<DashboardStats | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (status === 'unauthenticated') {
      router.push('/')
    } else if (session) {
      fetchStats()
    }
  }, [status, session, router])

  const fetchStats = async () => {
    try {
      setLoading(true)
      const response = await fetch('/api/dashboard')
      if (!response.ok) {
        throw new Error('Erro ao carregar estatísticas')
      }
      const data = await response.json()
      setStats(data.data)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Erro desconhecido')
    } finally {
      setLoading(false)
    }
  }

  const formatDate = (dateString: string): string => {
    const date = new Date(dateString)
    const day = String(date.getUTCDate()).padStart(2, '0')
    const month = String(date.getUTCMonth() + 1).padStart(2, '0')
    const year = date.getUTCFullYear()
    return `${day}/${month}/${year}`
  }

  const formatMonth = (monthString: string): string => {
    const [year, month] = monthString.split('-')
    const monthNames = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
    return `${monthNames[parseInt(month) - 1]}/${year}`
  }

  const getMaxValue = (data: Array<{ count: number }>) => {
    return Math.max(...data.map(d => d.count), 1)
  }

  if (status === 'loading' || loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-lg">Carregando dashboard...</div>
      </div>
    )
  }

  if (!session) {
    return null
  }

  if (error) {
    return (
      <div className="max-w-7xl mx-auto">
        <div className="bg-red-50 border border-red-200 rounded-md p-4">
          <p className="text-red-800">{error}</p>
        </div>
      </div>
    )
  }

  if (!stats) {
    return null
  }

  return (
    <div className="max-w-7xl mx-auto">
      {/* Header */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900">Dashboard</h1>
        <p className="mt-2 text-gray-600">
          Bem-vindo, {session.user.name}! Aqui está um resumo dos seus registros médicos.
        </p>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
        <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-lg shadow-lg p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-blue-100 text-sm font-medium">Total de Consultas</p>
              <p className="text-4xl font-bold mt-2">{stats.summary.totalConsultations}</p>
            </div>
            <div className="bg-blue-400 bg-opacity-30 rounded-full p-3">
              <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
              </svg>
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-br from-orange-500 to-orange-600 rounded-lg shadow-lg p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-orange-100 text-sm font-medium">Total de Eventos</p>
              <p className="text-4xl font-bold mt-2">{stats.summary.totalEpisodes}</p>
            </div>
            <div className="bg-orange-400 bg-opacity-30 rounded-full p-3">
              <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z" />
              </svg>
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-br from-green-500 to-green-600 rounded-lg shadow-lg p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-green-100 text-sm font-medium">Profissionais</p>
              <p className="text-4xl font-bold mt-2">{stats.summary.totalProfessionals}</p>
            </div>
            <div className="bg-green-400 bg-opacity-30 rounded-full p-3">
              <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
              </svg>
            </div>
          </div>
        </div>

        <div className="bg-gradient-to-br from-purple-500 to-purple-600 rounded-lg shadow-lg p-6 text-white">
          <div className="flex items-center justify-between">
            <div>
              <p className="text-purple-100 text-sm font-medium">Arquivos</p>
              <p className="text-4xl font-bold mt-2">{stats.summary.totalFiles}</p>
            </div>
            <div className="bg-purple-400 bg-opacity-30 rounded-full p-3">
              <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
              </svg>
            </div>
          </div>
        </div>
      </div>

      {/* Charts Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
        {/* Consultas por Especialidade */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Consultas por Especialidade</h2>
          {stats.bySpecialty.length > 0 ? (
            <div className="space-y-3">
              {stats.bySpecialty.slice(0, 5).map((item, index) => {
                const percentage = (item.count / getMaxValue(stats.bySpecialty)) * 100
                return (
                  <div key={index}>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-gray-700 font-medium">{item.name}</span>
                      <span className="text-gray-500">{item.count}</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div
                        className="bg-blue-600 h-2 rounded-full transition-all duration-500"
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                )
              })}
            </div>
          ) : (
            <p className="text-gray-500 text-sm">Nenhum dado disponível</p>
          )}
        </div>

        {/* Consultas por Clínica */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Consultas por Clínica</h2>
          {stats.byClinic.length > 0 ? (
            <div className="space-y-3">
              {stats.byClinic.slice(0, 5).map((item, index) => {
                const percentage = (item.count / getMaxValue(stats.byClinic)) * 100
                return (
                  <div key={index}>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-gray-700 font-medium">{item.name}</span>
                      <span className="text-gray-500">{item.count}</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div
                        className="bg-green-600 h-2 rounded-full transition-all duration-500"
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                )
              })}
            </div>
          ) : (
            <p className="text-gray-500 text-sm">Nenhum dado disponível</p>
          )}
        </div>

        {/* Consultas por Ano */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Consultas por Ano</h2>
          {stats.byYear.length > 0 ? (
            <div className="space-y-3">
              {stats.byYear.map((item, index) => {
                const percentage = (item.count / getMaxValue(stats.byYear)) * 100
                return (
                  <div key={index}>
                    <div className="flex justify-between text-sm mb-1">
                      <span className="text-gray-700 font-medium">{item.year}</span>
                      <span className="text-gray-500">{item.count}</span>
                    </div>
                    <div className="w-full bg-gray-200 rounded-full h-2">
                      <div
                        className="bg-purple-600 h-2 rounded-full transition-all duration-500"
                        style={{ width: `${percentage}%` }}
                      />
                    </div>
                  </div>
                )
              })}
            </div>
          ) : (
            <p className="text-gray-500 text-sm">Nenhum dado disponível</p>
          )}
        </div>

        {/* Evolução Mensal */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Evolução Mensal (Últimos 12 Meses)</h2>
          {stats.byMonth.length > 0 ? (
            <div className="space-y-4">
              <div className="flex items-end justify-between h-48 gap-1 pb-12">
                {stats.byMonth.slice(-12).map((item, index) => {
                  const percentage = (item.count / getMaxValue(stats.byMonth)) * 100
                  return (
                    <div key={index} className="flex-1 flex flex-col items-center">
                      <div className="relative w-full flex flex-col items-center justify-end h-full">
                        <span className="text-xs font-semibold text-indigo-700 mb-1">
                          {item.count}
                        </span>
                        <div
                          className="w-full bg-indigo-600 rounded-t hover:bg-indigo-700 transition-all duration-300"
                          style={{ height: `${percentage * 1.3}px`, minHeight: '20px' }}
                        />
                      </div>
                    </div>
                  )
                })}
              </div>
              <div className="flex justify-between gap-1">
                {stats.byMonth.slice(-12).map((item, index) => (
                  <div key={index} className="flex-1 text-center">
                    <span className="text-xs text-gray-500 inline-block transform -rotate-45 origin-center whitespace-nowrap">
                      {formatMonth(item.month)}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          ) : (
            <p className="text-gray-500 text-sm">Nenhum dado disponível</p>
          )}
        </div>
      </div>

      {/* Bottom Section */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Top Profissionais */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Profissionais Mais Consultados</h2>
          {stats.byProfessional.length > 0 ? (
            <div className="space-y-3">
              {stats.byProfessional.slice(0, 8).map((item, index) => (
                <div key={index} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors">
                  <div className="flex items-center gap-3">
                    <div className="bg-blue-100 text-blue-600 rounded-full w-8 h-8 flex items-center justify-center font-bold text-sm">
                      {index + 1}
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-900">{item.name}</p>
                      <p className="text-xs text-gray-500">{item.specialty}</p>
                    </div>
                  </div>
                  <span className="text-sm font-semibold text-blue-600">{item.count}</span>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-gray-500 text-sm">Nenhum dado disponível</p>
          )}
        </div>

        {/* Profissionais Melhor Avaliados */}
        <div className="bg-white rounded-lg shadow p-6">
          <h2 className="text-lg font-semibold text-gray-900 mb-4">Profissionais Melhor Avaliados</h2>
          {stats.topRatedProfessionals.length > 0 ? (
            <div className="space-y-3">
              {stats.topRatedProfessionals.map((item, index) => (
                <div key={index} className="flex items-center justify-between p-3 bg-gradient-to-r from-yellow-50 to-yellow-100 rounded-lg hover:from-yellow-100 hover:to-yellow-200 transition-colors">
                  <div className="flex items-center gap-3">
                    <div className="bg-yellow-400 text-white rounded-full w-8 h-8 flex items-center justify-center font-bold text-sm">
                      {index + 1}
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-900">{item.name}</p>
                      <p className="text-xs text-gray-600">{item.specialty}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="flex items-center justify-end gap-1">
                      <span className="text-sm font-semibold text-yellow-600">{item.averageRating}</span>
                      <svg className="w-4 h-4 text-yellow-400 fill-yellow-400" viewBox="0 0 20 20">
                        <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                      </svg>
                    </div>
                    <p className="text-xs text-gray-600 mt-1">
                      {item.totalRatings} {item.totalRatings === 1 ? 'avaliação' : 'avaliações'}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <p className="text-gray-500 text-sm text-center py-8">Nenhuma avaliação registrada</p>
          )}
        </div>

        {/* Consultas Recentes */}
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Consultas Recentes</h2>
            <Link href="/consultations?type=CONSULTATION" className="text-sm text-blue-600 hover:text-blue-700">
              Ver todas →
            </Link>
          </div>
          {stats.recentConsultations.length > 0 ? (
            <div className="space-y-3">
              {stats.recentConsultations.map((item) => (
                <Link
                  key={item.id}
                  href={`/consultations/${item.id}`}
                  className="block p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-sm font-medium text-gray-900">{item.professionalName}</p>
                      <p className="text-xs text-gray-500 mt-1">{item.specialty}</p>
                    </div>
                    <span className="text-xs text-gray-600">{formatDate(item.date)}</span>
                  </div>
                </Link>
              ))}
            </div>
          ) : (
            <div className="text-center py-8">
              <p className="text-gray-500 text-sm mb-4">Nenhuma consulta registrada ainda</p>
              <Link
                href="/consultations/new"
                className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 text-sm"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
                Nova Consulta
              </Link>
            </div>
          )}
        </div>

        {/* Eventos Recentes */}
        <div className="bg-white rounded-lg shadow p-6">
          <div className="flex justify-between items-center mb-4">
            <h2 className="text-lg font-semibold text-gray-900">Eventos Recentes</h2>
            <Link href="/consultations?type=EVENT" className="text-sm text-orange-600 hover:text-orange-700">
              Ver todos →
            </Link>
          </div>
          {stats.recentEpisodes.length > 0 ? (
            <div className="space-y-3">
              {stats.recentEpisodes.map((item) => (
                <Link
                  key={item.id}
                  href={`/consultations/${item.id}`}
                  className="block p-3 bg-gray-50 rounded-lg hover:bg-gray-100 transition-colors"
                >
                  <div className="flex justify-between items-start">
                    <div>
                      <p className="text-sm font-medium text-gray-900">{item.title}</p>
                    </div>
                    <span className="text-xs text-gray-600">{formatDate(item.date)}</span>
                  </div>
                </Link>
              ))}
            </div>
          ) : (
            <div className="text-center py-8">
              <p className="text-gray-500 text-sm mb-4">Nenhum evento registrado ainda</p>
              <Link
                href="/consultations/new"
                className="inline-flex items-center px-4 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700 text-sm"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                </svg>
                Novo Evento
              </Link>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// frontend/src/routes/Dashboard.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { push } from '@keenmate/svelte-spa-router'
  import { currentUser } from '../lib/auth'
  import * as api from '../lib/api'
  import type { DashboardStats } from '../lib/api'

  let stats = $state<DashboardStats | null>(null)
  let loading = $state(true)
  let error = $state('')

  onMount(async () => {
    try {
      stats = await api.getDashboard()
    } catch (e: unknown) {
      error = e instanceof Error ? e.message : 'Erro ao carregar dashboard'
    } finally {
      loading = false
    }
  })

  function formatDate(iso: string): string {
    const d = new Date(iso)
    return d.toLocaleDateString('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' })
  }

  function formatMonth(m: string): string {
    const [year, month] = m.split('-')
    const names = ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
    return `${names[parseInt(month) - 1]}/${year.slice(2)}`
  }

  function maxCount(arr: Array<{ count: number }>): number {
    return Math.max(...arr.map(d => d.count), 1)
  }
</script>

<div class="page">
  <div class="page-header">
    <h1>Dashboard</h1>
    <p class="subtitle">Bem-vindo, {$currentUser?.name}!</p>
  </div>

  {#if loading}
    <div class="loading">Carregando...</div>
  {:else if error}
    <p class="error-msg">{error}</p>
  {:else if stats}
    <!-- Summary Cards -->
    <div class="summary-grid">
      <div class="card card-blue">
        <div class="card-label">Consultas</div>
        <div class="card-value">{stats.summary.totalConsultations}</div>
      </div>
      <div class="card card-orange">
        <div class="card-label">Outros registros</div>
        <div class="card-value">{stats.summary.totalEpisodes}</div>
      </div>
      <div class="card card-green">
        <div class="card-label">Profissionais</div>
        <div class="card-value">{stats.summary.totalProfessionals}</div>
      </div>
      <div class="card card-purple">
        <div class="card-label">Arquivos</div>
        <div class="card-value">{stats.summary.totalFiles}</div>
      </div>
    </div>

    <!-- Charts Row -->
    <div class="charts-grid">
      <!-- By Specialty -->
      <div class="panel">
        <h2>Por Especialidade</h2>
        {#if stats.bySpecialty.length > 0}
          <div class="bar-list">
            {#each stats.bySpecialty.slice(0, 8) as item}
              <div class="bar-row">
                <span class="bar-label">{item.name}</span>
                <div class="bar-track">
                  <div class="bar bar-blue" style="width: {(item.count / maxCount(stats.bySpecialty)) * 100}%"></div>
                </div>
                <span class="bar-count">{item.count}</span>
              </div>
            {/each}
          </div>
        {:else}
          <p class="empty-hint">Nenhum dado disponível</p>
        {/if}
      </div>

      <!-- By Clinic -->
      <div class="panel">
        <h2>Por Clínica</h2>
        {#if stats.byClinic.length > 0}
          <div class="bar-list">
            {#each stats.byClinic.slice(0, 8) as item}
              <div class="bar-row">
                <span class="bar-label">{item.name}</span>
                <div class="bar-track">
                  <div class="bar bar-green" style="width: {(item.count / maxCount(stats.byClinic)) * 100}%"></div>
                </div>
                <span class="bar-count">{item.count}</span>
              </div>
            {/each}
          </div>
        {:else}
          <p class="empty-hint">Nenhum dado disponível</p>
        {/if}
      </div>

      <!-- By Year -->
      <div class="panel">
        <h2>Por Ano</h2>
        {#if stats.byYear.length > 0}
          <div class="bar-list">
            {#each stats.byYear as item}
              <div class="bar-row">
                <span class="bar-label">{item.year}</span>
                <div class="bar-track">
                  <div class="bar bar-purple" style="width: {(item.count / maxCount(stats.byYear)) * 100}%"></div>
                </div>
                <span class="bar-count">{item.count}</span>
              </div>
            {/each}
          </div>
        {:else}
          <p class="empty-hint">Nenhum dado disponível</p>
        {/if}
      </div>

      <!-- By Month -->
      <div class="panel panel-wide">
        <h2>Evolução Mensal (12 meses)</h2>
        {#if stats.byMonth.length > 0}
          <div class="month-chart">
            {#each stats.byMonth as item}
              <div class="month-col">
                <span class="month-count">{item.count}</span>
                <div class="month-bar-wrap">
                  <div
                    class="month-bar"
                    style="height: {Math.max((item.count / maxCount(stats.byMonth)) * 120, 4)}px"
                  ></div>
                </div>
                <span class="month-label">{formatMonth(item.month)}</span>
              </div>
            {/each}
          </div>
        {:else}
          <p class="empty-hint">Nenhum dado disponível</p>
        {/if}
      </div>
    </div>

    <!-- Bottom Row -->
    <div class="bottom-grid">
      <!-- Top Professionals -->
      <div class="panel">
        <h2>Mais Consultados</h2>
        {#if stats.byProfessional.length > 0}
          <div class="ranked-list">
            {#each stats.byProfessional as item, i}
              <div class="ranked-item">
                <span class="rank">{i + 1}</span>
                <div class="ranked-info">
                  <div class="ranked-name">{item.name}</div>
                  {#if item.specialty}
                    <div class="ranked-sub">{item.specialty}</div>
                  {/if}
                </div>
                <span class="ranked-count">{item.count}</span>
              </div>
            {/each}
          </div>
        {:else}
          <p class="empty-hint">Nenhum dado disponível</p>
        {/if}
      </div>

      <!-- Top Rated -->
      <div class="panel">
        <h2>Melhor Avaliados</h2>
        {#if stats.topRatedProfessionals.length > 0}
          <div class="ranked-list">
            {#each stats.topRatedProfessionals as item, i}
              <div class="ranked-item ranked-item-gold">
                <span class="rank rank-gold">{i + 1}</span>
                <div class="ranked-info">
                  <div class="ranked-name">{item.name}</div>
                  {#if item.specialty}
                    <div class="ranked-sub">{item.specialty}</div>
                  {/if}
                </div>
                <div class="rating-info">
                  <span class="rating-value">★ {item.averageRating}</span>
                  <span class="rating-count">{item.totalRatings} aval.</span>
                </div>
              </div>
            {/each}
          </div>
        {:else}
          <p class="empty-hint">Nenhuma avaliação registrada</p>
        {/if}
      </div>

      <!-- Recent Consultations -->
      <div class="panel">
        <div class="panel-header">
          <h2>Consultas Recentes</h2>
          <button class="link-btn" onclick={() => push('/consultations')}>Ver todas →</button>
        </div>
        {#if stats.recentConsultations.length > 0}
          <div class="recent-list">
            {#each stats.recentConsultations as item}
              <div class="recent-item" onclick={() => push(`/consultations/${item.id}`)} role="button" tabindex="0" onkeydown={(e) => e.key === 'Enter' && push(`/consultations/${item.id}`)}>
                <div class="recent-info">
                  <div class="recent-name">{item.professionalName}</div>
                  <div class="recent-sub">{item.specialty}</div>
                </div>
                <span class="recent-date">{formatDate(item.date)}</span>
              </div>
            {/each}
          </div>
        {:else}
          <p class="empty-hint">Nenhuma consulta registrada</p>
        {/if}
      </div>
    </div>
  {/if}
</div>

<style>
  .page-header {
    display: flex;
    align-items: baseline;
    gap: 16px;
    margin-bottom: 24px;
  }

  .subtitle {
    color: var(--text-muted);
    font-size: 14px;
  }

  .summary-grid {
    display: grid;
    grid-template-columns: repeat(4, 1fr);
    gap: 16px;
    margin-bottom: 24px;
  }

  .card {
    border-radius: var(--radius);
    padding: 20px 24px;
    color: #fff;
  }

  .card-blue   { background: linear-gradient(135deg, #2563eb, #3b82f6); }
  .card-orange { background: linear-gradient(135deg, #ea580c, #f97316); }
  .card-green  { background: linear-gradient(135deg, #16a34a, #22c55e); }
  .card-purple { background: linear-gradient(135deg, #7c3aed, #a855f7); }

  .card-label {
    font-size: 12px;
    opacity: 0.85;
    margin-bottom: 8px;
    font-weight: 500;
  }

  .card-value {
    font-size: 36px;
    font-weight: 700;
    line-height: 1;
  }

  .charts-grid {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 16px;
    margin-bottom: 16px;
  }

  .panel-wide {
    grid-column: span 2;
  }

  .bottom-grid {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    gap: 16px;
  }

  .panel {
    background: var(--bg-surface);
    border: 1px solid var(--border);
    border-radius: var(--radius);
    padding: 20px;
  }

  .panel h2 {
    font-size: 14px;
    font-weight: 600;
    color: var(--text);
    margin-bottom: 16px;
  }

  .panel-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 16px;
  }

  .panel-header h2 {
    margin-bottom: 0;
  }

  .link-btn {
    background: none;
    border: none;
    color: var(--accent);
    font-size: 12px;
    cursor: pointer;
    padding: 0;
  }

  .bar-list {
    display: flex;
    flex-direction: column;
    gap: 10px;
  }

  .bar-row {
    display: grid;
    grid-template-columns: 130px 1fr 32px;
    align-items: center;
    gap: 10px;
  }

  .bar-label {
    font-size: 12px;
    color: var(--text-muted);
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .bar-track {
    background: var(--bg-elevated);
    border-radius: 3px;
    height: 8px;
    overflow: hidden;
  }

  .bar {
    height: 100%;
    border-radius: 3px;
    transition: width 0.4s ease;
  }

  .bar-blue   { background: #3b82f6; }
  .bar-green  { background: #22c55e; }
  .bar-purple { background: #a855f7; }

  .bar-count {
    font-size: 12px;
    color: var(--text-muted);
    text-align: right;
  }

  /* Month chart */
  .month-chart {
    display: flex;
    align-items: flex-end;
    gap: 6px;
    height: 160px;
    padding-bottom: 28px;
  }

  .month-col {
    flex: 1;
    display: flex;
    flex-direction: column;
    align-items: center;
    height: 100%;
    justify-content: flex-end;
  }

  .month-count {
    font-size: 10px;
    color: var(--text-muted);
    margin-bottom: 4px;
  }

  .month-bar-wrap {
    flex: 1;
    display: flex;
    align-items: flex-end;
    width: 100%;
  }

  .month-bar {
    width: 100%;
    background: #4a9eff;
    border-radius: 3px 3px 0 0;
    min-height: 4px;
    transition: height 0.4s ease;
  }

  .month-label {
    font-size: 9px;
    color: var(--text-muted);
    margin-top: 4px;
    transform: rotate(-45deg);
    white-space: nowrap;
    display: block;
  }

  /* Ranked lists */
  .ranked-list {
    display: flex;
    flex-direction: column;
    gap: 8px;
  }

  .ranked-item {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 10px 12px;
    background: var(--bg-elevated);
    border-radius: var(--radius);
  }

  .ranked-item-gold {
    background: rgba(234, 179, 8, 0.08);
  }

  .rank {
    width: 24px;
    height: 24px;
    border-radius: 50%;
    background: rgba(74, 158, 255, 0.2);
    color: var(--accent);
    font-size: 11px;
    font-weight: 700;
    display: flex;
    align-items: center;
    justify-content: center;
    flex-shrink: 0;
  }

  .rank-gold {
    background: rgba(234, 179, 8, 0.2);
    color: #eab308;
  }

  .ranked-info {
    flex: 1;
    min-width: 0;
  }

  .ranked-name {
    font-size: 13px;
    font-weight: 500;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .ranked-sub {
    font-size: 11px;
    color: var(--text-muted);
  }

  .ranked-count {
    font-size: 13px;
    font-weight: 600;
    color: var(--accent);
  }

  .rating-info {
    text-align: right;
  }

  .rating-value {
    display: block;
    font-size: 13px;
    font-weight: 600;
    color: #eab308;
  }

  .rating-count {
    font-size: 10px;
    color: var(--text-muted);
  }

  /* Recent list */
  .recent-list {
    display: flex;
    flex-direction: column;
    gap: 6px;
  }

  .recent-item {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 10px 12px;
    background: var(--bg-elevated);
    border-radius: var(--radius);
    cursor: pointer;
    transition: background 0.2s;
  }

  .recent-item:hover {
    background: rgba(74, 158, 255, 0.1);
  }

  .recent-name {
    font-size: 13px;
    font-weight: 500;
  }

  .recent-sub {
    font-size: 11px;
    color: var(--text-muted);
  }

  .recent-date {
    font-size: 11px;
    color: var(--text-muted);
    white-space: nowrap;
    margin-left: 8px;
  }

  .empty-hint {
    font-size: 13px;
    color: var(--text-muted);
    text-align: center;
    padding: 20px 0;
  }

  @media (max-width: 900px) {
    .summary-grid { grid-template-columns: repeat(2, 1fr); }
    .charts-grid  { grid-template-columns: 1fr; }
    .panel-wide   { grid-column: span 1; }
    .bottom-grid  { grid-template-columns: 1fr; }
  }
</style>
