// components/navigation.tsx
'use client'

import { useSession, signIn, signOut } from 'next-auth/react'
import Link from 'next/link'
import { usePathname } from 'next/navigation'

export function Navigation() {
  const { data: session, status } = useSession()
  const pathname = usePathname()

  const navigation = [
    { name: 'Consultas', href: '/consultations' },
    { name: 'Profissionais', href: '/professionals' },
    { name: 'Relatórios', href: '/reports' },
  ]

  const adminNavigation = [
    { name: 'Administração', href: '/admin' },
  ]

  if (status === 'loading') {
    return (
      <nav className="bg-white shadow-sm border-b">
        <div className="container mx-auto px-4">
          <div className="flex justify-between items-center h-16">
            <Link href="/" className="text-xl font-bold text-gray-900">
              MedLog
            </Link>
            <div className="text-sm text-gray-500">Carregando...</div>
          </div>
        </div>
      </nav>
    )
  }

  return (
    <nav className="bg-white shadow-sm border-b">
      <div className="container mx-auto px-4">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center space-x-8">
            <Link href="/" className="text-xl font-bold text-gray-900">
              MedLog
            </Link>

            {session && (
              <div className="hidden md:flex space-x-4">
                {navigation.map((item) => (
                  <Link
                    key={item.name}
                    href={item.href}
                    className={`px-3 py-2 rounded-md text-sm font-medium ${
                      pathname === item.href
                        ? 'bg-gray-100 text-gray-900'
                        : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50'
                    }`}
                  >
                    {item.name}
                  </Link>
                ))}

                {session.user.role === 'ADMIN' && adminNavigation.map((item) => (
                  <Link
                    key={item.name}
                    href={item.href}
                    className={`px-3 py-2 rounded-md text-sm font-medium ${
                      pathname === item.href
                        ? 'bg-gray-100 text-gray-900'
                        : 'text-gray-600 hover:text-gray-900 hover:bg-gray-50'
                    }`}
                  >
                    {item.name}
                  </Link>
                ))}
              </div>
            )}
          </div>

          <div className="flex items-center space-x-4">
            {session ? (
              <div className="flex items-center space-x-4">
                <span className="text-sm text-gray-700">
                  Olá, {session.user.name}
                </span>
                <button
                  onClick={() => signOut()}
                  className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50"
                >
                  Sair
                </button>
              </div>
            ) : (
              <button
                onClick={() => signIn()}
                className="px-4 py-2 text-sm font-medium text-white bg-blue-600 rounded-md hover:bg-blue-700"
              >
                Entrar
              </button>
            )}
          </div>
        </div>
      </div>
    </nav>
  )
}

// frontend/src/components/Navigation.svelte
<script lang="ts">
  import { link, location, push } from '@keenmate/svelte-spa-router'
  import { currentUser, isAdmin, signout } from '../lib/auth'

  async function handleSignout() {
    await signout()
    push('/signin')
  }
</script>

<nav>
  <div class="nav-brand">MedLog</div>
  <div class="nav-links">
    <a href="/consultations" use:link class:active={$location === '/consultations' || $location === '/'}>
      Consultas
    </a>
    <a href="/professionals" use:link class:active={$location.startsWith('/professionals')}>
      Profissionais
    </a>
    <a href="/reports" use:link class:active={$location === '/reports'}>
      Relatórios
    </a>
    {#if $isAdmin}
      <a href="/admin" use:link class:active={$location === '/admin'}>
        Admin
      </a>
    {/if}
  </div>
  <div class="nav-user">
    {#if $currentUser}
      <span class="user-name">{$currentUser.name}</span>
      {#if $currentUser.role === 'ADMIN'}
        <span class="badge badge-yellow">Admin</span>
      {/if}
      <button class="btn btn-ghost btn-sm" onclick={handleSignout}>Sair</button>
    {/if}
  </div>
</nav>

<style>
  nav {
    display: flex;
    align-items: center;
    gap: 24px;
    background: var(--bg-surface);
    border-bottom: 1px solid var(--border);
    padding: 0 24px;
    height: 52px;
    position: sticky;
    top: 0;
    z-index: 100;
  }

  .nav-brand {
    font-size: 18px;
    font-weight: 700;
    color: var(--accent);
    letter-spacing: -0.02em;
  }

  .nav-links {
    display: flex;
    gap: 4px;
    flex: 1;
  }

  .nav-links a {
    padding: 6px 14px;
    border-radius: var(--radius);
    color: var(--text-muted);
    font-size: 14px;
    text-decoration: none;
    transition: color 0.2s, background 0.2s;
  }

  .nav-links a:hover {
    color: var(--text);
    background: var(--bg-elevated);
    text-decoration: none;
  }

  .nav-links a.active {
    color: var(--accent);
    background: rgba(74, 158, 255, 0.1);
  }

  .nav-user {
    display: flex;
    align-items: center;
    gap: 10px;
    margin-left: auto;
  }

  .user-name {
    font-size: 13px;
    color: var(--text-muted);
  }

  .btn-sm {
    padding: 4px 12px;
    font-size: 13px;
  }
</style>
