// frontend/src/routes/SignIn.svelte
<script lang="ts">
  import { push } from '@keenmate/svelte-spa-router'
  import { signin } from '../lib/auth'
  import { currentUser } from '../lib/auth'

  let email = $state('')
  let password = $state('')
  let loading = $state(false)
  let error = $state('')

  // Redirect if already signed in
  $effect(() => {
    if ($currentUser) {
      push('/consultations')
    }
  })

  async function handleSubmit(e: Event) {
    e.preventDefault()
    if (!email || !password) return
    loading = true
    error = ''
    try {
      await signin(email, password)
      push('/consultations')
    } catch (err: unknown) {
      error = err instanceof Error ? err.message : 'Falha ao entrar'
    } finally {
      loading = false
    }
  }
</script>

<div class="signin-page">
  <div class="signin-card">
    <div class="signin-header">
      <h1>MedLog</h1>
      <p>Prontuário médico familiar</p>
    </div>

    <form onsubmit={handleSubmit}>
      <div class="form-group">
        <label for="email">E-mail</label>
        <input
          id="email"
          type="email"
          bind:value={email}
          placeholder="seu@email.com"
          disabled={loading}
          required
        />
      </div>

      <div class="form-group">
        <label for="password">Senha</label>
        <input
          id="password"
          type="password"
          bind:value={password}
          placeholder="••••••••"
          disabled={loading}
          required
        />
      </div>

      {#if error}
        <p class="error-msg">{error}</p>
      {/if}

      <button type="submit" class="btn btn-primary" style="width:100%" disabled={loading}>
        {loading ? 'Entrando...' : 'Entrar'}
      </button>
    </form>
  </div>
</div>

<style>
  .signin-page {
    min-height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
    background: var(--bg);
    padding: 20px;
  }

  .signin-card {
    background: var(--bg-surface);
    border: 1px solid var(--border);
    border-radius: 10px;
    padding: 40px;
    width: 100%;
    max-width: 380px;
  }

  .signin-header {
    text-align: center;
    margin-bottom: 32px;
  }

  .signin-header h1 {
    font-size: 28px;
    font-weight: 700;
    color: var(--accent);
    margin-bottom: 6px;
  }

  .signin-header p {
    color: var(--text-muted);
    font-size: 14px;
  }
</style>

// app/auth/signin/page.tsx
'use client'

import { signIn } from 'next-auth/react'
import { useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import Image from 'next/image'

export default function SignInPage() {
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const router = useRouter()
  const params = useSearchParams()

  const callbackUrl = params.get('callbackUrl') || '/consultations'

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setError(null)
    const res = await signIn('credentials', {
      redirect: false,
      email,
      password,
      callbackUrl,
    })
    setLoading(false)
    if (res?.error) {
      setError('Credenciais inválidas')
      return
    }
    router.push(callbackUrl)
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 px-4">
      <div className="max-w-md w-full space-y-8">
        <div className="text-center">
          <div className="flex justify-center mb-4">
            <Image
              src="/doctor-icon.png"
              alt="MedLog"
              width={80}
              height={80}
              className="rounded-lg"
            />
          </div>
          <h2 className="text-3xl font-extrabold text-gray-900">MedLog</h2>
          <p className="mt-2 text-sm text-gray-600">
            Use seu email e senha cadastrados
          </p>
        </div>
        <form onSubmit={handleSubmit} className="mt-8 space-y-6 bg-white p-6 rounded shadow">
          {error && <div className="text-red-600 text-sm">{error}</div>}
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700">Email</label>
              <input
                type="email"
                required
                value={email}
                onChange={e => setEmail(e.target.value)}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
              />
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700">Senha</label>
              <input
                type="password"
                required
                value={password}
                onChange={e => setPassword(e.target.value)}
                className="mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
              />
            </div>
          </div>
          <div>
            <button
              type="submit"
              disabled={loading}
              className="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 disabled:opacity-50"
            >
              {loading ? 'Entrando...' : 'Entrar'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
